---
permissions:
  contents: write
  pull-requests: write

name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          release-type: simple
          package-name: luarocks-build-treesitter-parser
          signoff: "Marc Jakobi<marc@jakobi.dev>"
